own redis v1
alem-platform/foundation pull request #27
Opened 2024-10-07 09:22 UTC by Darwin939

2024-10-10 05:29 UTC, atlekbai requested changes
- Не составлено согласно типовым README как у Markov Chain. Например использование `#` вместо `##`.
- Давай операции SET и GET сделаем как у самого redis'а
- Нет упоминаний на каком порту должен запускаться сервер
- Нет инструкции как должен запускаться бинарник
- Проект выглядит еще сырым и нужно поработать еще над текстом

2024-10-29 06:16 UTC, atlekbai requested changes
На этот раз уже получше! Нужно добавить условие про concurrency, чтобы использовали либо mutex'ы или sync.Map. Потом в тестах проверять на обработку параллельных запросов

2024-10-29 06:16 UTC, atlekbai commented on own-redis/README.md
> +- basic networking concept
```suggestion
- Basic networking concepts
```

2024-10-29 06:16 UTC, atlekbai commented on own-redis/README.md
> +A striking example of such databases are:
```suggestion
Examples of such databases are:
```

2024-10-29 06:16 UTC, atlekbai commented on own-redis/README.md
> +- [Dynomydb](https://aws.amazon.com/dynamodb/)
Разве MongoDB является in-memory key-value хранилищем?
Я думаю что примерами лучше оставить Redis и Memcached

2024-10-29 06:16 UTC, atlekbai commented on own-redis/README.md
> +The `SET` command supports option `PX` that modify its behavior:
Что значит `PX`? Какая расшифровка?

2024-10-29 06:16 UTC, atlekbai commented on own-redis/README.md
> +
Переписать Abstract, согласно всему проекту. Сделать текст более професиональным

2024-10-29 11:04 UTC, Darwin939 commented on own-redis/README.md
> +The `SET` command supports option `PX` that modify its behavior:
Взял из документации редиса PX milliseconds -- Set the specified expire time, in milliseconds (a positive integer)
[Ссыль](https://redis.io/docs/latest/commands/set/)

2024-10-29 11:07 UTC, Darwin939 commented on own-redis/README.md
> +- [Dynomydb](https://aws.amazon.com/dynamodb/)
ok. Убрал

2024-10-30 10:06 UTC, Darwin939 commented on own-redis/README.md
> +
ок

2024-11-03 11:08 UTC, atlekbai commented on own-redis/README.md
> +This project will enhance your understanding of networking and database principles
```suggestion
This project will enhance your understanding of networking and database principles.
```

2024-11-03 11:09 UTC, atlekbai commented on own-redis/README.md
> +Writing a key-value store via REST API would be too easy, wouldn't it? Let's make it a bit more complicated and let the client and your application communicate using the UDP protocol, i.e. each reque
```suggestion
Writing a key-value store via REST API would be too easy, wouldn't it? Let's make it a bit more complicated and let the client and your application communicate using the UDP protocol, i.e. each request and response is a single UDP packet. In our key-value store implementation you have to implement three methods SET, GET and PING. SET puts a key-value and GET gets and returns the given value back to the client. The PING command verifies that the storage is working.
```

2024-11-03 11:10 UTC, atlekbai commented on own-redis/README.md
Много где не хватает точек в конце предложений. Надо пройтись по тексту и расставить точки.

2024-11-03 11:11 UTC, atlekbai commented on own-redis/README.md
> +If the client tries to insert a value into an existing key, your application should update the value to the last value specified by the client (new)
Почему в конце предложения стоит `(new)`?

2024-11-03 11:12 UTC, atlekbai commented on own-redis/README.md
> +- Your program will be tested with parallel/competitive requests. To avoid data races, you need to use synchronization primitives from the [sync](https://pkg.go.dev/sync) package
Данный `Note` лучше перенести в раздел `### SET`

2024-11-05 17:31 UTC, Darwin939 commented on own-redis/README.md
> +- Your program will be tested with parallel/competitive requests. To avoid data races, you need to use synchronization primitives from the [sync](https://pkg.go.dev/sync) package
ok

2024-11-06 04:21 UTC, atlekbai approved these changes

2024-11-06 04:21 UTC, merged