A Library for Others
alem-platform/foundation pull request #5
Opened 2024-07-23 11:58 UTC by Adilyam

1) Есть сомнения в блоке как билдить и тестить (там код на go) возможно это нужно поменять или улучшить

2) Названия функций тоже можно поменять

3) Есть предположение, что со строками это будет легко сделать, может поменять на массив байтов?

2024-07-29 04:11 UTC, atlekbai requested changes

2024-08-02 08:04 UTC, Adilyam commented
Я изменила часть, но буду еще смотреть

2024-08-05 11:39 UTC, atlekbai requested changes

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +```
Давай уберем это правило, потому что проект не будет компилироваться, а будет импортироваться

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +- Only built-in packages are allowed. If not, you will get `0` grade.
Это нужно подправить что никакой пакет нельзя использовать, кроме `io.Reader`

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +> Each time ReadCSVLine is called, you should read only until newline. Avoid reading the entire file at once and then processing each line.
Надо сюда добавить требования, что если в линии не хватает или лишняя кавычка, то должна возвращать пустую строку и ошибку ErrQuote

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +> Each time ReadCSVLine is called, you should read only until newline. Avoid reading the entire file at once and then processing each line.
Почему это условие добавлено - `Return nil if memory limit exceeded`?

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +> Each time ReadCSVLine is called, you should read only until newline. Avoid reading the entire file at once and then processing each line.
Эту линию можно убрать - `Using `bufio` is forbidden`

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +- Returns nil if n < 0 or beyond last field
Это условие надо исправить, чтобы возвращал ошибку ErrFieldCount

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +- Behavior undefined if called before ReadCSVLine is called
Отсылка к C  😄

2024-08-05 11:39 UTC, atlekbai commented on a-library-for-others/README.md
> +- Allowed packages: "fmt", "os"
Тоже надо убрать

2024-08-05 11:42 UTC, atlekbai requested changes

2024-08-05 11:42 UTC, atlekbai commented on a-library-for-others/README.md
> +
Добавь сюда пункт, что в этом проекте нужно использовать метод `Read(b []byte)`, чтобы читать лини

2024-08-07 09:26 UTC, atlekbai approved these changes

2024-08-07 09:27 UTC, merged